// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBahg2lC1vPetOBrwbCsLod1j7_YQKpLso',
    appId: '1:682156982618:web:f2bb7cc9c70cb0db6db363',
    messagingSenderId: '682156982618',
    projectId: 'chatapplication-6cde1',
    authDomain: 'chatapplication-6cde1.firebaseapp.com',
    storageBucket: 'chatapplication-6cde1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK5u2hH8X6gIBQFuLux65tr_hB2WUm6mE',
    appId: '1:682156982618:android:6d237bf49630b5d86db363',
    messagingSenderId: '682156982618',
    projectId: 'chatapplication-6cde1',
    storageBucket: 'chatapplication-6cde1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-A5nymBDS2PDmQP7GQso7dKTk8dbKSt0',
    appId: '1:682156982618:ios:6286bcb7ca53a3766db363',
    messagingSenderId: '682156982618',
    projectId: 'chatapplication-6cde1',
    storageBucket: 'chatapplication-6cde1.appspot.com',
    androidClientId: '682156982618-m0o5ohlfguo2bd4q3rb1ca1if6j29hj4.apps.googleusercontent.com',
    iosClientId: '682156982618-jcq3bdb6uo42pd84pe516mo2kh22h57c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-A5nymBDS2PDmQP7GQso7dKTk8dbKSt0',
    appId: '1:682156982618:ios:6286bcb7ca53a3766db363',
    messagingSenderId: '682156982618',
    projectId: 'chatapplication-6cde1',
    storageBucket: 'chatapplication-6cde1.appspot.com',
    androidClientId: '682156982618-m0o5ohlfguo2bd4q3rb1ca1if6j29hj4.apps.googleusercontent.com',
    iosClientId: '682156982618-jcq3bdb6uo42pd84pe516mo2kh22h57c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );
}
